sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install tox flake8 pylint
language: python
script:
- flake8 switchmate --max-line-length=120
- pylint switchmate --max-line-length=120
